debug:
    enabled: false

logging:
    # version: 1
    # incremental: False
    # disable_existing_loggers: True
    default_level: info
    default_logger: root
    default_handler: console
    default_formatter: generic
    root:
        level: info
        handlers:
            - console
    loggers:
        ingo:
            handlers:
                - console
        web:
            handlers:
                - console
        routes:
            qualname: routes.middleware
    handlers:
        console:
            class: logging.StreamHandler
            args: "(sys.stderr,)"
            formatter: generic
        # file:
        #   class : logging.handlers.RotatingFileHandler
        #   filename: logconfig.log
        #   maxBytes: 1024
        #   backupCount: 3
    formatters:
        color:
            class: ingo.log.formatters.ColorFormatter
            format: "%(asctime)s, %(msecs)03d %(levelname)-5.5s [%(name)s] %(message)s"
            datefmt: "%H:%M:%S"
        generic:
            class: logging.Formatter
            format: "%(asctime)s, %(msecs)03d %(levelname)-5.5s [%(name)s] %(message)s"
            datefmt: "%H:%M:%S"

plugins:
    load_all: False
    enabled: 